services:
  jenkins-controller:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-controller
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  ssh-agent:
    build:
      context: .
      dockerfile: Dockerfile.ssh_agent
    container_name: jenkins-ssh-agent
    restart: unless-stopped
    ports:
      - "2222:22"

  ansible-agent:
    build:
      context: .
      dockerfile: Dockerfile.ansible_agent
    container_name: jenkins-ansible-agent
    restart: unless-stopped
    ports:
      - "2223:22"
  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test_server
    container_name: test-server
    restart: unless-stopped
    ports:
      - "2224:22"
volumes:
  jenkins_home:
