version: "3.8"

services:
  lab03-cron:
    build: .
    container_name: lab03-cron
    environment:
      API_URL: "http://host.docker.internal:8080/"
      API_KEY: "DMITRIIGACHAYEV"
      # Таймзона для корректного времени в cron и date
      TZ: "Europe/Chisinau"
    volumes:
      # Сохраняем выгруженные JSON-ы на хосте (скрипт пишет в /app/data)
      - ./data:/app/data
      # Лог cron-а на хост
      - ./cron.log:/var/log/cron.log
    restart: unless-stopped
